/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.austral.ingsis.printscript.app;


import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
    }
}
